### ISSUE TITLE
`Transport()` is not finished and hanging with `self.socket.recv()`

### ISSUE THREAD

**Issue by rohjunha** [alters-mit/transport_challenge#8]
I have installed the latest version of `transport_challenge`, tried to run `m=Transport()`.
It has not finished for a long time and I got a message when I interrupted the code:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/projects/transport_challenge/transport_challenge/transport_controller.py", line 138, in __init__
    super().__init__(port=port, launch_build=launch_build, screen_width=screen_width, screen_height=screen_height,
  File "/home/mai/jroh/miniconda3/envs/tdw/lib/python3.8/site-packages/magnebot/magnebot_controller.py", line 344, in __init__
    super().__init__(port=port, launch_build=launch_build, check_version=check_pypi_version)
  File "/home/mai/jroh/miniconda3/envs/tdw/lib/python3.8/site-packages/tdw/controller.py", line 50, in __init__
    self.socket.recv()
  File "zmq/backend/cython/socket.pyx", line 781, in zmq.backend.cython.socket.Socket.recv
  File "zmq/backend/cython/socket.pyx", line 817, in zmq.backend.cython.socket.Socket.recv
  File "zmq/backend/cython/socket.pyx", line 186, in zmq.backend.cython.socket._recv_copy
  File "zmq/backend/cython/checkrc.pxd", line 13, in zmq.backend.cython.checkrc._check_rc
KeyboardInterrupt
```

Here is a list of pip packages regarding the repository:
* tdw version: 1.8.7.0
* magnebot version: 1.1.2

**Comment by alters-mit** [comment]
@rohjunha  Closing this ticket. This error means that you have a lingering simulation ("build") process running. Kill that process and re-run your controller+build and it will work.
